# -*- coding: utf-8 -*-
"""Streamlit_Obesity.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BqtGIu-tG61nto2XtG78o5TG9FH_xm7t
"""

!pip install streamlit
!pip install openpyxl
import streamlit as st
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

st.title("📊 Análise de Obesidade com Machine Learning")

# --- 1. Carregar dados diretamente ---
dados = pd.read_excel("Obesity 5.0.xlsx")  # arquivo na mesma pasta
st.write("Prévia dos dados:", dados.head())

# --- 2. Preparar dados ---
dados['Altura'] = pd.to_numeric(dados['Altura'], errors='coerce')
dados.loc[dados['Altura'] > 3.0, 'Altura'] /= 100
dados['Altura'] = dados['Altura'].round(2)

dados['Peso'] = pd.to_numeric(dados['Peso'], errors='coerce')
dados.loc[dados['Peso'] > 400, 'Peso'] /= 1000
dados['Peso'] = dados['Peso'].astype(int)

dados['IMC'] = dados['Peso'] / (dados['Altura'] ** 2)

bins = [0, 18.5, 24.9, 29.9, 34.9, 39.9, np.inf]
labels = ['Abaixo do Peso','Peso Normal','Sobrepeso','Obesidade Grau I','Obesidade Grau II','Obesidade Grau III']
dados['Obesidade'] = pd.cut(dados['IMC'], bins=bins, labels=labels)

dados_encoded = pd.get_dummies(
    dados,
    columns=['Gênero','Frequência_Alimentar_Calorica','Comer_Entre_Refeições','Consumo_Alcool'],
    drop_first=True
)

# --- 3. Treino/Teste ---
y = dados_encoded['Obesidade']
X = dados_encoded.drop(columns=['IMC','Obesidade'])

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = RandomForestClassifier(random_state=42)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

# --- Por quê do modelo? ---

st.markdown(""" Optou-se pelo algoritmo Random Forest por se tratar de um problema de classificação supervisionada multiclasse, onde o objetivo é prever diferentes níveis de obesidade. O Random Forest se mostrou adequado porque lida bem com variáveis numéricas e categóricas, reduz o risco de overfitting ao combinar diversas árvores de decisão e permite identificar a importância das variáveis na previsão. Além disso, é um modelo robusto e amplamente utilizado em problemas de saúde e comportamento, garantindo boa acurácia e interpretabilidade. """)

# --- 4. Resultados ---
st.subheader("📈 Resultados do Modelo")
acuracia_raw = accuracy_score(y_test, y_pred)
st.write("Acurácia (valor bruto):", acuracia_raw)
st.write(f"Assertividade total (em porcentagem): {acuracia_raw * 100:.2f}%")
st.text("Relatório de Classificação:\n" + classification_report(y_test, y_pred))

# --- 5. Matriz de Confusão ---
st.subheader("🔍 Matriz de Confusão")
fig, ax = plt.subplots(figsize=(8,6))
class_names = labels
conf_matrix = confusion_matrix(y_test, y_pred, labels=class_names)
sns.heatmap(conf_matrix, annot=True, fmt='d', cmap='Blues',
            xticklabels=class_names, yticklabels=class_names, ax=ax)
st.pyplot(fig)

st.markdown(""" A matriz de confusão revela que o modelo teve bom desempenho na classificação das categorias intermediárias, como sobrepeso (93 acertos) e obesidade grau I (82 acertos), mas apresentou confusões entre categorias vizinhas, como peso normal e sobrepeso, ou obesidade grau I e II. Esses erros são compreensíveis à luz dos dados analisados. Distribuição de idade: as faixas etárias médias entre categorias vizinhas são próximas, especialmente entre sobrepeso e obesidade grau I, o que pode dificultar a distinção pelo modelo. Hábitos alimentares e de atividade física: muitos indivíduos com sobrepeso e obesidade grau I compartilham padrões semelhantes de consumo de alimentos calóricos e baixa prática de exercícios, o que reduz a separação entre classes. Diferenças entre gêneros: como os dados mostram que mulheres concentram-se mais em obesidade grau III e homens em sobrepeso e grau II, o modelo pode ter aprendido padrões mais claros para esses grupos, mas menos precisos para extremos ou faixas menos representadas. Essas relações indicam que os erros do modelo não são aleatórios, mas refletem sobreposições reais nos dados. Isso reforça a importância de considerar variáveis complementares — como estilo de vida, histórico familiar e consumo de vegetais — para melhorar a acurácia nas classificações mais difíceis. """)

# --- Paleta personalizada ---
paleta_personalizada = {
    'Abaixo do Peso': 'lightgreen',
    'Peso Normal': 'green',
    'Sobrepeso': 'gold',
    'Obesidade Grau I': 'orange',
    'Obesidade Grau II': 'red',
    'Obesidade Grau III': 'darkred'
}

# --- 6. Distribuição por gênero ---
st.subheader("👩 Distribuição da Obesidade (Feminino)")
dados_feminino = dados[dados['Gênero'] == 'Feminino']
contagem_feminino = dados_feminino['Obesidade'].value_counts().reindex(labels, fill_value=0)
fig, ax = plt.subplots(figsize=(10,5))
sns.barplot(
    x=contagem_feminino.index,
    y=contagem_feminino.values,
    palette=[paleta_personalizada[cat] for cat in contagem_feminino.index],
    order=labels,
    ax=ax
)
ax.set_title("Distribuição da Obesidade entre Pessoas do Gênero Feminino")
ax.set_ylabel("")
ax.set_yticks([])
for container in ax.containers:
    ax.bar_label(container, fmt='%d', label_type='edge', padding=3)
plt.xticks(rotation=45, ha='right')
st.pyplot(fig)

st.markdown(""" Entre mulheres, o maior número de casos está na categoria de obesidade grau III, o que contrasta com os dados masculinos, onde essa categoria é quase inexistente. Isso indica uma prevalência mais alta de obesidade severa entre mulheres, o que exige atenção especial em estratégias de prevenção e intervenção precoce. """)

st.subheader("👨 Distribuição da Obesidade (Masculino)")
dados_masculino = dados[dados['Gênero'] == 'Masculino']
contagem_masculino = dados_masculino['Obesidade'].value_counts().reindex(labels, fill_value=0)
fig, ax = plt.subplots(figsize=(10,5))
sns.barplot(
    x=contagem_masculino.index,
    y=contagem_masculino.values,
    palette=[paleta_personalizada[cat] for cat in contagem_masculino.index],
    order=labels,
    ax=ax
)
ax.set_title("Distribuição da Obesidade entre Pessoas do Gênero Masculino")
ax.set_ylabel("")
ax.set_yticks([])
for container in ax.containers:
    ax.bar_label(container, fmt='%d', label_type='edge', padding=3)
plt.xticks(rotation=45, ha='right')
st.pyplot(fig)

st.markdown(""" A maior parte dos homens está concentrada nas categorias de sobrepeso e obesidade grau II, indicando que o excesso de peso é predominante, mas os casos mais graves (grau III) são raros. Isso sugere que, embora o problema seja amplo, ainda há espaço para intervenções antes que evolua para quadros clínicos mais críticos. """)

# --- 7. Média de idade por categoria ---
st.subheader("📊 Média de Idade por Categoria de Obesidade (Feminino)")
media_idade_fem = dados_feminino.groupby('Obesidade')['Idade'].mean().reindex(labels)
fig, ax = plt.subplots(figsize=(10,5))
sns.barplot(
    x=media_idade_fem.index,
    y=media_idade_fem.values,
    palette=[paleta_personalizada[cat] for cat in media_idade_fem.index],
    order=labels,
    ax=ax
)
ax.set_ylabel("Média de Idade")
for container in ax.containers:
    ax.bar_label(container, fmt='%.1f', label_type='edge', padding=3)
plt.xticks(rotation=45, ha='right')
st.pyplot(fig)

st.markdown(""" A distribuição da média de idade entre as categorias de obesidade feminina mostra uma progressão até a obesidade grau I, com pico de idade média em 27 anos. A partir daí, observa-se uma leve queda: mulheres com obesidade grau II têm média de 25 anos, e aquelas com obesidade grau III, 23 anos. Esse padrão sugere que os casos mais graves de obesidade estão se manifestando em mulheres mais jovens, o que pode indicar um início precoce de hábitos alimentares inadequados, sedentarismo ou fatores metabólicos. """)

st.subheader("📊 Média de Idade por Categoria de Obesidade (Masculino)")
media_idade_masc = dados_masculino.groupby('Obesidade')['Idade'].mean().reindex(labels)
fig, ax = plt.subplots(figsize=(10,5))
sns.barplot(
    x=media_idade_masc.index,
    y=media_idade_masc.values,
    palette=[paleta_personalizada[cat] for cat in media_idade_masc.index],
    order=labels,
    ax=ax
)
ax.set_ylabel("Média de Idade")
for container in ax.containers:
    ax.bar_label(container, fmt='%.1f', label_type='edge', padding=3)
plt.xticks(rotation=45, ha='right')
st.pyplot(fig)

st.markdown(""" A distribuição da média de idade entre as categorias de obesidade masculina revela padrões onde os homens com **obesidade grau II** apresentam a maior média de idade (28,4 anos), enquanto os com **obesidade grau III** têm a menor média (18,0 anos). Esse contraste pode indicar que os casos mais graves de obesidade estão se manifestando em indivíduos mais jovens, o que é preocupante do ponto de vista clínico e epidemiológico. Por outro lado, a progressão entre as categorias *peso normal*, *sobrepeso* e *obesidade grau I* mostra um aumento gradual da média de idade, sugerindo que o ganho de peso pode estar relacionado ao envelhecimento e à mudança de hábitos ao longo do tempo. Esse padrão reforça a importância de intervenções precoces, especialmente entre jovens com obesidade grau III, que podem estar expostos a riscos metabólicos mais cedo e por mais tempo. A análise também destaca a necessidade de estratégias diferenciadas por faixa etária, considerando que os fatores associados à obesidade podem variar conforme o estágio da vida. """)

